### ISSUE TITLE
VM Crash on P9 after Fuel Materialization

### ISSUE THREAD

**Issue by seandenigris** [tesonep/pharo-talents#11]
P9-64bit via Launcher on M1 Mac. 

1. Load Talents and Fuel via:
```smalltalk
[ Metacello new
	baseline: 'Talents';
	repository: 'github://tesonep/pharo-talents';
	load ] ensure: [ EpMonitor current enable ].

Metacello new
    repository: 'github://theseion/Fuel:4.1.0';
    baseline: 'Fuel';
    load.
```
2. Create a class and a Trait (and instVar accessors for both):
```smalltalk
Object subclass: #MyClass
	instanceVariableNames: 'cvar' 
	classVariableNames: ''
	package: ''.

Trait named: #TMyTrait
	instanceVariableNames: 'tvar'
	package: ''.
```
3. Inspect:
```smalltalk
obj := MyClass new.
obj cvar: 2.
obj addTalent: TMyTrait.
obj tvar: 3.
self assert: obj cvar = 2.
self assert: obj tvar = 3.

filename := (FileLocator imageDirectory / 'obj.fuel') fullName.

FLSerializer new
		object: obj;
		filePath: filename;
		serialize.
		
materialization := FLMaterializer new
		filePath: filename;
		materialize.
objCopy := materialization root.
```
4. The trait's instVar seems to have disappeared, although the print string looks like that of a Talented object:
<img width="901" alt="Screen Shot 2022-01-07 at 6 46 28 PM" src="https://user-images.githubusercontent.com/184176/148621214-6036fe3a-fe5f-46f4-b20a-7a8c20bfb47e.png">
5. Crash the image from the workspace from step 3 with: `objCopy tvar`

Not sure if this is a Talents problem or a Fuel problem (or both).

cc @thesion @tesonep 

[crash.dmp.txt](https://github.com/tesonep/pharo-talents/files/7831899/crash.dmp.txt)

**Comment by seandenigris** [comment]
Inspecting the last statement of this script from theseion/Fuel/issues/240, with a `#var` accessor added, seems to return random data (and sometimes crash):
```smalltalk
Trait named: #Talentable
	 uses: {}
	 slots: { #var }
	 package: 'Fuel-Talents'.
	
talented := Object new addTalent: Talentable.

FLSerializer new
	object: talented;
	streamFactory: [ (FileLocator imageDirectory / 'talent.fuel') ensureCreateFile binaryWriteStream ];
	serialize.
mat :FLMaterializer new
	streamFactory: [ (FileLocator imageDirectory / 'talent.fuel') binaryReadStream ];
	materialize.

	
mat := root var
```

**Comment by theseion** [comment]
Let's assume the bug issue is in Fuel. It's possible that I messed something up the class layout. I've opened an issue: https://github.com/theseion/Fuel/issues/262.

**Comment by theseion** [comment]
@tesonep you can close this issue. I have a working fix in Fuel.

**Comment by seandenigris** [comment]
Awesome news! Thanks @theseion :)

**Comment by seandenigris** [comment]
I confirm Fuel 5.0.1 fixes the issue. Thanks again everyone 🥳
